### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by hardillb** [Rice0/WatsonSysArchChatbot#1]
Hi,

Thank you for creating a Node-RED node.

Would it possible for you to rename your node to something like node-red-contrib-leanix-watson so it falls in line with the naming guidelines (https://nodered.org/docs/creating-nodes/packaging#naming) and makes it clear that is it not supported by the core Node-RED team.

Thanks

**Comment by EricFernandezDC** [comment]
Hi,

Really sorry for this, I was just changing everything and I forgot about the contrib part! Already uploaded it, is there a way to take the previous node down? 

Many thanks!

**Comment by EricFernandezDC** [comment]
Node-red-leanix-watson has been taken down, thank you, you can now find it at https://www.npmjs.com/package/node-red-contrib-leanix-watson 👍
